---
#Rules to be applied using linter
whitelist_rules:
- closing_brace
- closure_end_indentation
- closure_spacing
- colon
- comma
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- explicit_self
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- literal_expression_end_indentation
- mark
- no_space_in_method_call
- opening_brace
- operator_usage_whitespace
- prefer_self_type_over_type_of_self
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_void_return
- return_arrow_whitespace
- sorted_first_last
- sorted_imports
- statement_position
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- unneeded_parentheses_in_closure_argument
- unused_closure_parameter
- unused_control_flow_label
- unused_import
- vertical_whitespace
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces


closing_brace:
 severity: error

closure_end_indentation:
 severity: error

closure_spacing:
 severity: error

colon:
 severity: error

comma:
 severity: error

empty_enum_arguments:
 severity: error

empty_parameters:
 severity: error

empty_parentheses_with_trailing_closure:
 severity: error

explicit_init:
 severity: error

explicit_self:
 severity: error

leading_whitespace:
 severity: error

legacy_cggeometry_functions:
 severity: error

legacy_constant:
 severity: error

legacy_constructor:
 severity: error

legacy_nsgeometry_functions:
 severity: error

literal_expression_end_indentation:
 severity: error

mark:
 severity: error

no_space_in_method_call:
 severity: error

opening_brace:
 severity: error

operator_usage_whitespace:
 severity: error

prefer_self_type_over_type_of_self:
 severity: error

protocol_property_accessors_order:
 severity: error

redundant_discardable_let:
 severity: error

redundant_nil_coalescing:
 severity: error

redundant_objc_attribute:
 severity: error

redundant_void_return:
 severity: error

return_arrow_whitespace:
 severity: error

sorted_first_last:
 severity: error

sorted_imports:
 severity: error

statement_position:
 severity: error

trailing_comma:
 severity: error

trailing_newline:
 severity: error

trailing_semicolon:
 severity: error

trailing_whitespace:
 severity: error

unneeded_parentheses_in_closure_argument:
 severity: error

unused_closure_parameter:
 severity: error

unused_control_flow_label:
 severity: error

unused_import:
 severity: error

vertical_whitespace:
 severity: error

vertical_whitespace_between_cases:
 severity: error

vertical_whitespace_closing_braces:
 severity: error

vertical_whitespace_opening_braces:
 severity: error

excluded:
- Pods
