---
#Rules to be applied using linter
whitelist_rules:
- block_based_kvo
- class_delegate_protocol
- closure_parameter_position
- collection_alignment
- compiler_protocol_init
- conditional_returns_on_newline
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_object_literal
- duplicate_enum_cases
- duplicate_imports
- empty_collection_literal
- empty_count
- empty_string
- empty_xctest_method
- expiring_todo
- explicit_enum_raw_value
- explicit_init
- explicit_top_level_acl
- explicit_type_interface
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_name_no_space
- first_where
- flatmap_over_map_reduce
- implicit_getter
- last_where
- legacy_hashing
- let_var_whitespace
- lower_acl_than_parent
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- no_fallthrough_only
- nsobject_prefer_isequal
- operator_whitespace
- overridden_super_call
- override_in_extension
- private_action
- private_outlet
- private_over_fileprivate
- prohibited_super_call
- protocol_property_accessors_order
- quick_discouraged_call
- redundant_set_access_control
- single_test_class
- strict_fileprivate
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- unavailable_function
- unneeded_break_in_switch
- unowned_variable_capture
- unused_capture_list
- unused_declaration
- unused_enumerated
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- weak_delegate
- xct_specific_matcher
- xctfail_message

block_based_kvo:
 severity: error

class_delegate_protocol:
 severity: error

closure_parameter_position:
 severity: error

collection_alignment:
 severity: error

compiler_protocol_init:
 severity: error

conditional_returns_on_newline:
 severity: error

contains_over_filter_count:
 severity: error

contains_over_filter_is_empty:
 severity: error

contains_over_first_not_nil:
 severity: error

contains_over_range_nil_comparison:
 severity: error

control_statement:
 severity: error

deployment_target:
 severity: error
 iOS_deployment_target: 13.0

discarded_notification_center_observer:
 severity: error

discouraged_direct_init:
 severity: error

discouraged_object_literal:
 severity: error

duplicate_enum_cases:
 severity: error

duplicate_imports:
 severity: error

empty_collection_literal:
 severity: error

empty_count:
 severity: error

empty_string:
 severity: error

empty_xctest_method:
 severity: error

expiring_todo:
 severity: error

explicit_enum_raw_value:
 severity: error

explicit_init:
 severity: error

explicit_top_level_acl:
 severity: error

explicit_type_interface:
 severity: error

extension_access_modifier:
 severity: error

fallthrough:
 severity: error

fatal_error_message:
 severity: error

file_name_no_space:
 severity: error

first_where:
 severity: error

flatmap_over_map_reduce:
 severity: error

implicit_getter:
 severity: error

last_where:
 severity: error

legacy_hashing:
 severity: error

let_var_whitespace:
 severity: error

lower_acl_than_parent:
 severity: error

multiline_function_chains:
 severity: error

multiline_literal_brackets:
 severity: error

multiline_parameters:
 severity: error

multiline_parameters_brackets:
 severity: error

no_fallthrough_only:
 severity: error

nsobject_prefer_isequal:
 severity: error

operator_whitespace:
 severity: error

overridden_super_call:
 severity: error

override_in_extension:
 severity: error

private_action:
 severity: error

private_outlet:
 severity: error

private_over_fileprivate:
 severity: error

prohibited_super_call:
 severity: error

protocol_property_accessors_order:
 severity: error

quick_discouraged_call:
 severity: error

redundant_set_access_control:
 severity: error

single_test_class:
 severity: error

strict_fileprivate:
 severity: error

superfluous_disable_command:
 severity: error

switch_case_alignment:
 severity: error

switch_case_on_newline:
 severity: error

syntactic_sugar:
 severity: error

unavailable_function:
 severity: error

unneeded_break_in_switch:
 severity: error

unowned_variable_capture:
 severity: error

unused_capture_list:
 severity: error

unused_declaration:
 severity: error

unused_enumerated:
 severity: error

unused_optional_binding:
 severity: error

unused_setter_value:
 severity: error

valid_ibinspectable:
 severity: error

vertical_parameter_alignment:
 severity: error

weak_delegate:
 severity: error

xct_specific_matcher:
 severity: error

xctfail_message:
 severity: error

excluded:
- Pods
