coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.05%
        base: auto

    patch:
      default:
        # basic
        target: 85%
        threshold: 0%
        base: auto

ignore:
  - "Example/*/**"
  - "fastlane/*/**"   
  - "ChartsSwiftUI.podspec"